#! /usr/bin/env python
"""
subbands_corr2uvfits_wrapper.py
Runs corr2uvfits for a number of subbands with header files previously generated by split_ngas_header.py
"""

import sys, os

if (len(sys.argv) != 4):
    print 'Usage: python subbands_corr2uvfits [basename] [# of subbands] [cleanup 0=no,1=yes]'
else:

    basename = str(sys.argv[1])
    n_subbands = int(sys.argv[2])
    cleanup = int(sys.argv[3])
    tail_a = 'lacspc'
    tail_c = 'lccspc'
    
    for i in range(1,n_subbands+1):

        # If not averaging has been done then L-files have all caps filetypes

        if not os.path.exists(('%s_band%02d.' % (basename, i)) + tail_a):
            tail_a = 'LACSPC'
            tail_c = 'LCCSPC'
            if not os.path.exists(('%s_band%02d.' % (basename, i)) + tail_a):
                print 'Cannot find L-files corresponding to %s_band%02d' % (basename, i)
                continue

        cmd = "corr2uvfits -l -H %s_header_band%d.txt -a %s_band%02d.%s -c %s_band%02d.%s -o %s_band_%02d.uvfits" % (basename, i, basename, i, tail_a, basename, i, tail_c, basename, i) 
        print cmd
        os.system(cmd)

    if(cleanup):
        cmd = 'rm *gpu*.fits *.lccspc *.lacspc'
        os.system(cmd)

