"""empty message

Revision ID: 101c4a826ed0
Revises: 2c7136f1da7
Create Date: 2015-01-21 21:02:02.166277

"""

# revision identifiers, used by Alembic.
revision = '101c4a826ed0'
down_revision = '2c7136f1da7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_range',
    sa.Column('user', sa.String(length=32), nullable=True),
    sa.Column('range_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['range_id'], ['range.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.username'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_range')
    op.drop_table('range')
    ### end Alembic commands ###
