"""empty message

Revision ID: 1a649a6dcbd
Revises: 2da69084f47
Create Date: 2015-01-29 02:26:02.443824

"""

# revision identifiers, used by Alembic.
revision = '1a649a6dcbd'
down_revision = '2da69084f47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('range_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_comment_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'range', ['range_id'], ['id'])
    op.drop_column('comment', 'comment_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_comment_id_fkey', 'comment', 'range', ['comment_id'], ['id'])
    op.drop_column('comment', 'range_id')
    ### end Alembic commands ###
