"""empty message

Revision ID: 27cc57f3b67
Revises: 4c51647af66
Create Date: 2014-12-01 14:17:37.479375

"""

# revision identifiers, used by Alembic.
revision = '27cc57f3b67'
down_revision = '4c51647af66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histogram_data',
    sa.Column('obs_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('julian_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('obs_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histogram_data')
    ### end Alembic commands ###
