"""empty message

Revision ID: 2807610e9be
Revises: 4e630620516
Create Date: 2015-02-06 03:52:40.783392

"""

# revision identifiers, used by Alembic.
revision = '2807610e9be'
down_revision = '4e630620516'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
