"""empty message

Revision ID: 2c7136f1da7
Revises: 4c51647af66
Create Date: 2014-12-05 00:15:07.536706

"""

# revision identifiers, used by Alembic.
revision = '2c7136f1da7'
down_revision = '4c51647af66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histogram_data',
    sa.Column('obs_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('julian_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('obs_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histogram_data')
    ### end Alembic commands ###
