"""empty message

Revision ID: 309a5077439
Revises: 1a649a6dcbd
Create Date: 2015-01-30 05:40:02.261147

"""

# revision identifiers, used by Alembic.
revision = '309a5077439'
down_revision = '1a649a6dcbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('username', sa.String(length=32), nullable=True))
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['username'], ['username'])
    op.drop_column('comment', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['username'])
    op.drop_column('comment', 'username')
    ### end Alembic commands ###
