"""empty message

Revision ID: 4e630620516
Revises: 309a5077439
Create Date: 2015-02-06 00:12:19.773920

"""

# revision identifiers, used by Alembic.
revision = '4e630620516'
down_revision = '309a5077439'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_on', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_on')
    ### end Alembic commands ###
