"""empty message

Revision ID: 56530bc1b68
Revises: 2807610e9be
Create Date: 2015-02-06 03:54:56.372784

"""

# revision identifiers, used by Alembic.
revision = '56530bc1b68'
down_revision = '2807610e9be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
