"""empty message

Revision ID: 9323852082
Revises: 56530bc1b68
Create Date: 2015-02-06 03:57:57.513727

"""

# revision identifiers, used by Alembic.
revision = '9323852082'
down_revision = '56530bc1b68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
